name: Test Debezium UI Backend

on:
  push:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'backend/**'
      - '.github/workflows/backend-testing.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'backend/**'
      - '.github/workflows/backend-testing.yml'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    env:
      DEBEZIUM_VERSION: "v1.6.1.Final"
    steps:
      - name: Checkout Debezium main repository
        uses: actions/checkout@v2
        with:
          repository: debezium/debezium
          ref: ${{ env.DEBEZIUM_VERSION }}
          path: debezium
      - name: Checkout Debezium UI
        uses: actions/checkout@v2
        with:
          path: dbzui
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: dbzui-${{ runner.os }}-maven-${{ hashFiles('dbzui/pom.xml', 'dbzui/**/pom.xml') }}
          restore-keys: |
            dbzui-${{ runner.os }}-maven-
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache local Yarn repository
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: dbzui-${{ runner.os }}-yarn-${{ hashFiles('dbzui/ui/yarn.lock') }}
          restore-keys: |
            dbzui-${{ runner.os }}-yarn-
      - name: Build debezium-checkstyle
        run: mvn clean install -f debezium/pom.xml -pl support/checkstyle -DskipTests -DskipITs
      - name: Test Debezium UI Backend
        run: mvn clean install -f dbzui -B -Ddebezium.test.records.waittime=20 -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
