name: Test Debezium UI Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'pom.xml'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBEZIUM_VERSION: "v1.5.0.Alpha1"
    steps:
      - name: Checkout Debezium main repository
        uses: actions/checkout@v2
        with:
          repository: debezium/debezium
          ref: ${{ env.DEBEZIUM_VERSION }}
          path: debezium
      - name: Checkout Debezium UI
        uses: actions/checkout@v2
        with:
          path: ui
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', '**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build debezium-checkstyle
        run: mvn clean install -f debezium/pom.xml -pl support/checkstyle -DskipTests -DskipITs
      - name: Test Debezium UI
        run: mvn clean install -f ui -B -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
